#!/bin/bash
#
function help(){
echo -e "\033[30m 黑色字 \033[0m"
echo -e "\033[31m 红色字 \033[0m" 
echo -e "\033[32m 绿色字 \033[0m" 
echo -e "\033[33m 黄色字 \033[0m" 
echo -e "\033[34m 蓝色字 \033[0m" 
echo -e "\033[35m 紫色字 \033[0m" 
echo -e "\033[36m 天蓝字 \033[0m" 
echo -e "\033[37m 白色字 \033[0m" 
}
#help
function myred(){
	echo -e "\033[31m $1 \033[0m"
}
function mygreen(){
	echo -e "\033[32m $1 \033[0m"
}
function myyellow(){
	echo -e "\033[33m $1 \033[0m"
}
function myblue(){
	echo -e "\033[34m $1 \033[0m"
}
function mypurple(){
	echo -e "\033[35m $1 \033[0m"
}

function mycerulean(){
	echo -e "\033[36m $1 \033[0m"
}
